version: '3.8'
services:
  postgres:
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: config_db
      POSTGRES_USER: config_user
      POSTGRES_PASSWORD: config_password
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
