version: '3'
services:
  oracle:
    image: wnameless/oracle-xe-11g-r2
    ports:
      - "1521:1521"
      - "8080:8080"
    environment:
      - ORACLE_ALLOW_REMOTE=true
      - ORACLE_DISABLE_ASYNCH_IO=true
      - JAVA_TOOL_OPTIONS=-Djavax.net.ssl.trustStore=/u01/app/oracle/wallet/truststore.jks -Djavax.net.ssl.trustStorePassword=secure
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./jks:/u01/app/oracle/wallet
    restart: always
